name: testing

on:
  push:
    branches: [ main, trying, staging ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: test-bors
    # runs-on: [self-hosted, linux, x64]
    runs-on: [self-hosted, macOS, x64]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      RUSTFLAGS: -Zinstrument-coverage
      LLVM_PROFILE_FILE: "webusb-%p-%m.profraw"

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --test-threads=1
    - name: Generate coverage
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o ./lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lcov.info
